title = 'Chirpy'
enableGitInfo = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  tabWidth = 4
  wrapperClass = 'highlight'

[markup.goldmark.parser]
  wrapStandAloneImageWithinParagraph = false

[markup.goldmark.parser.attribute]
  block = true
  title = true
[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[module]
[[module.imports]]
  path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[module.imports]]
  path = "github.com/geekifan/chirpy-static-assets"

[[module.imports.mounts]]
  source = "."
  target = "static/lib"

