baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Chirpy'
enableGitInfo = true
paginate = 5  # 每页显示的文章数量

[taxonomies]
  category = "categories"
  tag = "tags"

[module]
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 10
  pre = "fa-solid fa-house"

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20
  pre = "fa-solid fa-stream"

[[menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30
  pre = "fa-solid fa-tags"

[[menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 40
  pre = "fa-solid fa-archive"

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 50
  pre = "fa-solid fa-info-circle"

[params]
  theme_version = "5.2.0"
  toc = true
  avatar = "img/commons/avatar.jpg"

[params.assets]
  self_host = false

[params.social]
  name = "Yifan"
  url = "https://www.yifan.com"
  [[params.social.links]]
    type = "github"
    id = "yourusername"  # 或直接使用 url = "https://github.com/yourusername"
    icon = "fab fa-github"
  
  [[params.social.links]]
    type = "twitter"
    id = "yourhandle"
    icon = "fab fa-twitter"
  
  [[params.social.links]]
    type = "email"
    id = "your.email@example.com"  # 会被自动分割处理
    icon = "fas fa-envelope"
  
  [[params.social.links]]
    type = "rss"
    icon = "fas fa-rss"
    noblank = true  # 不在新窗口打开