title = 'Chirpy'
enableGitInfo = true

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[languages]
  [languages.zh-CN]
    languageName = "中文"
    languageCode = "zh-CN"
    weight = 1

  [languages.en]
    languageName = "English"
    languageCode = "en"
    weight = 2

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = false
  tabWidth = 4
  wrapperClass = 'highlight'
[markup.goldmark.parser.attribute]
  block = true
  title = true
[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"

[module]
[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[languages.en.menu.main]]
  name = "Home"
  url = "/"
  weight = 10
  pre = "fa-house"

[[languages.en.menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 20
  pre = "fa-stream"

[[languages.en.menu.main]]
  name = "Tags"
  url = "/tags/"
  weight = 30
  pre = "fa-tags"

[[languages.en.menu.main]]
  name = "Archives"
  url = "/archives/"
  weight = 40
  pre = "fa-archive"

[[languages.en.menu.main]]
  name = "About"
  url = "/about/"
  weight = 50
  pre = "fa-info-circle"

[[languages.zh-CN.menu.main]]
  name = "主页"
  url = "/"
  weight = 10
  pre = "fa-house"

[[languages.zh-CN.menu.main]]
  name = "分类"
  url = "/categories/"
  weight = 20
  pre = "fa-stream"

[[languages.zh-CN.menu.main]]
  name = "标签"
  url = "/tags/"
  weight = 30
  pre = "fa-tags"

[[languages.zh-CN.menu.main]]
  name = "归档"
  url = "/archives/"
  weight = 40
  pre = "fa-archive"

[[languages.zh-CN.menu.main]]
  name = "关于"
  url = "/about/"
  weight = 50
  pre = "fa-info-circle"

[params]
  theme_version = "5.2.0"
  toc = true
  avatar = "img/commons/avatar.jpg"
  tagline = "A text-focused Jekyll theme"

[params.assets]
  self_host = false

[params.social]
  name = "Yifan"
  url = "https://github.com/geekifan"
  [[params.social.links]]
    type = "github"
    id = "yourusername"  # 或直接使用 url = "https://github.com/yourusername"
    icon = "fab fa-github"
  
  [[params.social.links]]
    type = "twitter"
    id = "yourhandle"
    icon = "fab fa-twitter"
  
  [[params.social.links]]
    type = "email"
    id = "your.email@example.com"  # 会被自动分割处理
    icon = "fas fa-envelope"
  
  [[params.social.links]]
    type = "rss"
    icon = "fas fa-rss"
    noblank = true  # 不在新窗口打开