[en]
  label = "English"
  locale = "en"
  weight = 2
  title = "Chirpy"
  [en.params]
    tagline = "A text-focused blog theme"

[zh-CN]
  label = "中文"
  locale = "zh-CN"
  weight = 1
  title = "Chirpy"
  [zh-CN.params]
    tagline = "一个专注于文本的博客主题"
