title = 'Chirpy'
enableGitInfo = true
theme = "hugo-theme-chirpy"
themesDir = "../../"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
hasCJKLanguage = true

[pagination]
  pagerSize = 5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  category = "categories"
  tag = "tags"
